# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: Default
  agent: Web App

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

  # Clean install dependencies
- script: |
    npm i
  displayName: 'Install dependencies'

  # Build your React app
- script: |
    npm run build
  displayName: 'Build React app'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist'          # 👈 Folder to publish (React's build output)
    ArtifactName: 'react-build'     # 👈 Name shown in pipeline summary
    publishLocation: 'Container'    # Store in Azure DevOps
  displayName: 'Publish build artifacts'
